version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lifesync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    environment:
      ENVIRONMENT: development
      SERVICE_VERSION: 1.0.0
      LOG_LEVEL: debug
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lifesync?sslmode=disable
      JWT_SECRET: ${JWT_SECRET:-development-secret-key}
      AUTH_SERVICE_PORT: 8080
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: