version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lifesync
      POSTGRES_USER: lifesync
      POSTGRES_PASSWORD: lifesync123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    build: ./services/auth-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://lifesync:lifesync123@postgres:5432/lifesync
      JWT_SECRET: your-secret-key-here
      PORT: 8080
    depends_on:
      - postgres
      - rabbitmq

  flowtime-service:
    build: ./services/flowtime-service
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://lifesync:lifesync123@postgres:5432/lifesync
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672
      JWT_SECRET: your-secret-key-here
      PORT: 3000
    depends_on:
      - postgres
      - rabbitmq

  api-gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      FLOWTIME_SERVICE_URL: http://flowtime-service:3000
    depends_on:
      - auth-service
      - flowtime-service

volumes:
  postgres_data: