version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lifesync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  auth-service:
    build: ./services/auth-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lifesync
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  flowtime-service:
    build: ./services/flowtime-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lifesync
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  # API Gateway (nginx)
  api-gateway:
    image: nginx:alpine
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - auth-service
      - flowtime-service

volumes:
  postgres_data: