name: flowtime
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Core dependencies
  device_preview: ^1.2.0
  flutter_riverpod: ^2.4.0
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_animate: ^4.2.0
  dartz: ^0.10.1
  
  # Database
  drift: ^2.14.0
  path_provider: ^2.1.2
  path: ^1.8.3
  drift_sqflite: ^2.0.1
  sqflite: ^2.2.8
  
  # Navigation
  go_router: ^16.0.0
  
  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  
  # Auth & Storage
  firebase_auth: ^5.6.2
  google_sign_in: ^7.1.1
  flutter_secure_storage: ^9.2.4
  sign_in_with_apple: ^7.0.1
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  
  # Network
  dio: ^5.8.0
  
  # Code generation dependencies
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  supabase_flutter: ^2.9.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code generation
  build_runner: ^2.4.13
  drift_dev: ^2.14.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/